# ---- Frontend Dockerfile ----
FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости Streamlit
COPY frontend/requirements.txt .
RUN pip install --default-timeout=100 --no-cache-dir -i https://pypi.org/simple -r requirements.txt


# Копируем Streamlit-приложение
COPY frontend /app

# Указываем порт
EXPOSE 8501

# Команда запуска
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]